### ISSUE TITLE
not converging

### ISSUE THREAD

**Issue by Shaunlipy** [freddyalfonsoboulton/crf_tutorial#1]
Hi, I followed your code, only changed all torch.cat to torch.stack (because torch.cat throws error: 
'''
prev_alpha = torch.cat(alpha_t).view(1,-1)
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
'''). 

And one more: in your function "simulate_data" should you add:

prev_state = next_state

inside your for loop? (I added)

my results:
...
Epoch 0: Batch 97/100 loss is 5.7809
Epoch 0: Batch 98/100 loss is 6.7747
Epoch 0: Batch 99/100 loss is 4.9654
[4 0 0 0 4 5 3 4 0 4 2 2 5 3 1]
[0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[-0.33391526 -0.6212296  -2.148588  ]
 [-0.8201128  -0.5577968  -0.9616032 ]]

Thanks

**Comment by freddyalfonsoboulton** [comment]
Hi Shaun,

Good catch! I think that's definitely a bug in simulate data. I think what was happening in your case is that the probabilities in the transition_mat made it so that the loaded die never came up which is why the model outputs a lot of zeros. 

I've made two changes to the code apart from the fix in simulate data:

1. Initialize Parameter weights with N(-1, 0.1). This should have been in the original code, I don't think it makes sense for the parameters to be positive in this case.

2. Used the following transition probabilities:
transition_mat = {'fair': np.array([0.6, 0.4, 0.0]),
                 'loaded': np.array([0.3, 0.7, 0.0]),
                 'start': np.array([0.5, 0.5, 0.0])}

The log loss still hovers between 7 and 6, but I think the predictions are satisfying.

Result on previously unseen roll:
roll: array([5, 3, 5, 3, 5, 1, 0, 3, 4, 4, 0, 2, 5, 5, 5])
prediction: array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1])
truth: array([1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1])

Thanks for going through my code again!

**Comment by freddyalfonsoboulton** [comment]
Also, 

I'm not really sure why torch.cat is throwing that error. I used torch 0.3.0 for this post so maybe torch 0.4 is causing the issue?

**Comment by Shaunlipy** [comment]
The "loaded" did show up. I tried the updated code twice, get the following:
1:
Epoch 0: Batch 96/100 loss is 7.7294
Epoch 0: Batch 97/100 loss is 7.7693
Epoch 0: Batch 98/100 loss is 3.9939
Epoch 0: Batch 99/100 loss is 7.3481
[0 5 0 2 1 4 4 5 0 0 0 2 1 5 5]
[1 1 1 0 0 0 0 0 1 0 0 0 0 0 0]
[0 1 0 0 0 0 1 1 0 0 0 0 1 1 1]
[[-0.86232877 -1.4046131  -1.0660524 ]
 [-1.402624   -0.6929721  -1.054203  ]]

2:
Epoch 0: Batch 97/100 loss is 4.7535
Epoch 0: Batch 98/100 loss is 7.1384
Epoch 0: Batch 99/100 loss is 5.2592
[5 2 0 3 5 3 5 5 5 5 0 4 1 5 5]
[1 1 1 0 0 0 1 1 1 1 0 1 0 0 0]
[1 0 1 0 1 1 1 1 1 1 0 1 0 1 1]
[[-0.8542588  -1.3834339  -0.82286984]
 [-1.3882279  -0.679252   -1.0393827 ]]

I'm more concerned about the transition matrix. What would be the desired values for the last column in the transition matrix?

Thanks.

**Comment by freddyalfonsoboulton** [comment]
They should be roughly equal since the start state is equally likely to be either fair or biased.

Looks like gradient descent worked a bit better in the first case but I think your results make sense in both cases.

**Comment by Shaunlipy** [comment]
Got it. I thought it needed to be 0.5 (or log(0.5) ) for both entries in the third column in transition matrix. 
Thanks
